
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        SiteRules
* GENERATION DATE:  16.06.2014
* CLASS FILE:       /home6/ptwogorg/public_html/adm/classgen/generated_classes/class.SiteRules.php
* FOR MYSQL TABLE:  siteRules
* FOR MYSQL DB:     ptwogorg_main
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class SiteRules
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $ID;   // KEY ATTR. WITH AUTOINCREMENT

var $Category;   // (normal Attribute)
var $Rule;   // (normal Attribute)
var $Value;   // (normal Attribute)
var $Notes;   // (normal Attribute)
var $IsActive;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function SiteRules()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getCategory()
{
return $this->Category;
}

function getRule()
{
return $this->Rule;
}

function getValue()
{
return $this->Value;
}

function getNotes()
{
return $this->Notes;
}

function getIsActive()
{
return $this->IsActive;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setCategory($val)
{
$this->Category =  $val;
}

function setRule($val)
{
$this->Rule =  $val;
}

function setValue($val)
{
$this->Value =  $val;
}

function setNotes($val)
{
$this->Notes =  $val;
}

function setIsActive($val)
{
$this->IsActive =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM siteRules WHERE ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->ID;

$this->Category = $row->Category;

$this->Rule = $row->Rule;

$this->Value = $row->Value;

$this->Notes = $row->Notes;

$this->IsActive = $row->IsActive;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM siteRules WHERE ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO siteRules ( Category,Rule,Value,Notes,IsActive ) VALUES ( '$this->Category','$this->Rule','$this->Value','$this->Notes','$this->IsActive' )";
$result = $this->database->query($sql);
$this->ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE siteRules SET  Category = '$this->Category',Rule = '$this->Rule',Value = '$this->Value',Notes = '$this->Notes',IsActive = '$this->IsActive' WHERE ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
