<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        StudentProfile
* GENERATION DATE:  16.06.2014
* CLASS FILE:       /home6/ptwogorg/public_html/adm/classgen/generated_classes/class.StudentProfile.php
* FOR MYSQL TABLE:  studentProfiles
* FOR MYSQL DB:     ptwogorg_main
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class StudentProfile
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $ID;   // KEY ATTR. WITH AUTOINCREMENT

var $StudentID;   // (normal Attribute)
var $Over18;   // (normal Attribute)
var $TravelRadius;   // (normal Attribute)
var $Address1;   // (normal Attribute)
var $Address2;   // (normal Attribute)
var $City;   // (normal Attribute)
var $State;   // (normal Attribute)
var $ZipCode;   // (normal Attribute)
var $Country;   // (normal Attribute)
var $IsActive;   // (normal Attribute)
var $CreatedOn;   // (normal Attribute)
var $Notes;   // (normal Attribute)
var $IPAddress;   // (normal Attribute)
var $ShowWelcome;   // (normal Attribute)
var $DOB; // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function StudentProfile()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getStudentID()
{
return $this->StudentID;
}

function getOver18()
{
return $this->Over18;
}

function getTravelRadius()
{
return $this->TravelRadius;
}

function getAddress1()
{
return $this->Address1;
}

function getAddress2()
{
return $this->Address2;
}

function getCity()
{
return $this->City;
}

function getState()
{
return $this->State;
}

function getZipCode()
{
return $this->ZipCode;
}

function getCountry()
{
return $this->Country;
}

function getIsActive()
{
return $this->IsActive;
}

function getCreatedOn()
{
return $this->CreatedOn;
}

function getNotes()
{
return $this->Notes;
}

function getIPAddress()
{
return $this->IPAddress;
}

function getShowWelcome()
{
return $this->ShowWelcome;
}

function getDOB()
{
return $this->DOB;
}
// **********************
// SETTER METHODS
// **********************


function setStudentID($val)
{
$this->StudentID =  $val;
}

function setOver18($val)
{
$this->Over18 =  $val;
}

function setTravelRadius($val)
{
$this->TravelRadius =  $val;
}

function setAddress1($val)
{
$this->Address1 =  $val;
}

function setAddress2($val)
{
$this->Address2 =  $val;
}

function setCity($val)
{
$this->City =  $val;
}

function setState($val)
{
$this->State =  $val;
}

function setZipCode($val)
{
$this->ZipCode =  $val;
}

function setCountry($val)
{
$this->Country =  $val;
}

function setIsActive($val)
{
$this->IsActive =  $val;
}

function setCreatedOn($val)
{
$this->CreatedOn =  $val;
}

function setNotes($val)
{
$this->Notes =  $val;
}

function setIPAddress($val)
{
$this->IPAddress =  $val;
}

function setShowWelcome($val)
{
$this->ShowWelcome =  $val;
}

function setDOB($val)
{
$this->DOB =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($StudentID)
{

$sql =  "SELECT * FROM studentProfiles WHERE StudentID = $StudentID;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysqli_fetch_object($result);


$this->StudentID = $row->StudentID;

$this->Over18 = $row->Over18;

$this->TravelRadius = $row->TravelRadius;

$this->Address1 = $row->Address1;

$this->Address2 = $row->Address2;

$this->City = $row->City;

$this->State = $row->State;

$this->ZipCode = $row->ZipCode;

$this->Country = $row->Country;

$this->IsActive = $row->IsActive;

$this->CreatedOn = $row->CreatedOn;

$this->Notes = $row->Notes;

$this->IPAddress = $row->IPAddress;

$this->ShowWelcome = $row->ShowWelcome;

$this->DOB = $row->DOB;
}

static function GetValueFromField($fieldname, $uid) {
	$sql = "SELECT $fieldname FROM studentProfiles WHERE StudentID = $uid;";
$result = $this->database->query($sql);
$result = $this->database->result;
$row = mysqli_fetch_array($result);
return $row[$fieldname];
	
}

// **********************
// DELETE
// **********************

function delete($StudentID)
{
$sql = "DELETE FROM studentProfiles WHERE StudentID = $StudentID;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO studentProfiles ( StudentID,Over18,TravelRadius,Address1,Address2,City,State,ZipCode,Country,IsActive,CreatedOn,Notes,IPAddress,ShowWelcome ) VALUES ( '$this->StudentID','$this->Over18','$this->TravelRadius','$this->Address1','$this->Address2','$this->City','$this->State','$this->ZipCode','$this->Country','$this->IsActive','$this->CreatedOn','$this->Notes','$this->IPAddress' ,'$this->ShowWelcome','$this->DOB')";
$result = $this->database->query($sql);
$this->ID = mysqli_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($StudentID)
{



$sql = " UPDATE studentProfiles SET  StudentID = '$this->StudentID',Over18 = '$this->Over18',TravelRadius = '$this->TravelRadius',Address1 = '$this->Address1',Address2 = '$this->Address2',City = '$this->City',State = '$this->State',ZipCode = '$this->ZipCode',Country = '$this->Country',IsActive = '$this->IsActive',CreatedOn = '$this->CreatedOn',Notes = '$this->Notes',IPAddress = '$this->IPAddress',ShowWelcome = '$this->ShowWelcome', DOB = '$this->DOB' WHERE StudentID = $StudentID ";

$result = $this->database->query($sql);



}


} // class : end

?>