<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        TutorTests
* GENERATION DATE:  21.05.2014
* CLASS FILE:       /home6/ptwogorg/public_html/adm/scg/generated_classes/class.TutorTests.php
* FOR MYSQL TABLE:  tutorTests
* FOR MYSQL DB:     ptwogorg_main
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class TutorTests
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $ID;   // KEY ATTR. WITH AUTOINCREMENT

var $CategoryID;   // (normal Attribute)
var $SubjectID;   // (normal Attribute)
var $Name;   // (normal Attribute)
var $CreatedBy;   // (normal Attribute)
var $CreatedOn;   // (normal Attribute)
var $AssignedTo;   // (normal Attribute)
var $Active;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function TutorTests()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getCategoryID()
{
return $this->CategoryID;
}

function getSubjectID()
{
return $this->SubjectID;
}

function getName()
{
return $this->Name;
}

function getCreatedBy()
{
return $this->CreatedBy;
}

function getCreatedOn()
{
return $this->CreatedOn;
}

function getAssignedTo()
{
return $this->AssignedTo;
}

function getActive()
{
return $this->Active;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setCategoryID($val)
{
$this->CategoryID =  $val;
}

function setSubjectID($val)
{
$this->SubjectID =  $val;
}

function setName($val)
{
$this->Name =  $val;
}

function setCreatedBy($val)
{
$this->CreatedBy =  $val;
}

function setCreatedOn($val)
{
$this->CreatedOn =  $val;
}

function setAssignedTo($val)
{
$this->AssignedTo =  $val;
}

function setActive($val)
{
$this->Active =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM tutorTests WHERE ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->ID;

$this->CategoryID = $row->CategoryID;

$this->SubjectID = $row->SubjectID;

$this->Name = $row->Name;

$this->CreatedBy = $row->CreatedBy;

$this->CreatedOn = $row->CreatedOn;

$this->AssignedTo = $row->AssignedTo;

$this->Active = $row->Active;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM tutorTests WHERE ID = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->ID = ""; // clear key for autoincrement

$sql = "INSERT INTO tutorTests ( CategoryID,SubjectID,Name,CreatedBy,CreatedOn,AssignedTo,Active ) VALUES ( '$this->CategoryID','$this->SubjectID','$this->Name','$this->CreatedBy','$this->CreatedOn','$this->AssignedTo','$this->Active' )";
$result = $this->database->query($sql);
$this->ID = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE tutorTests SET  CategoryID = '$this->CategoryID',SubjectID = '$this->SubjectID',Name = '$this->Name',CreatedBy = '$this->CreatedBy',CreatedOn = '$this->CreatedOn',AssignedTo = '$this->AssignedTo',Active = '$this->Active' WHERE ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>