
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Messages
* GENERATION DATE:  16.06.2014
* CLASS FILE:       /home6/ptwogorg/public_html/adm/classgen/generated_classes/class.Messages.php
* FOR MYSQL TABLE:  messages
* FOR MYSQL DB:     ptwogorg_main
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Messages
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $ID;   // KEY ATTR. WITH AUTOINCREMENT

var $MailBoxID;   // (normal Attribute)
var $SenderID;   // (normal Attribute)
var $RecipientID;   // (normal Attribute)
var $SubjectID;   // (normal Attribute)
var $Subject;   // (normal Attribute)
var $Body;   // (normal Attribute)
var $SentOn;   // (normal Attribute)
var $ReadOn;   // (normal Attribute)
var $DeletedOn;   // (normal Attribute)
var $Status;   // (normal Attribute)
var $ReplyID;   // (normal Attribute)
var $IsRead;   // (normal Attribute)
var $IsDeleted;   // (normal Attribute)
var $IsTrash;   // (normal Attribute)
var $SendType;   // (normal Attribute)
var $RecType;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Messages()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getID()
{
return $this->ID;
}

function getMailBoxID()
{
return $this->MailBoxID;
}

function getSenderID()
{
return $this->SenderID;
}

function getRecipientID()
{
return $this->RecipientID;
}

function getSubjectID()
{
return $this->SubjectID;
}

function getSubject()
{
return $this->Subject;
}

function getBody()
{
return $this->Body;
}

function getSentOn()
{
return $this->SentOn;
}

function getReadOn()
{
return $this->ReadOn;
}

function getDeletedOn()
{
return $this->DeletedOn;
}

function getStatus()
{
return $this->Status;
}

function getReplyID()
{
return $this->ReplyID;
}

function getIsRead()
{
return $this->IsRead;
}

function getIsDeleted()
{
return $this->IsDeleted;
}

function getIsTrash()
{
return $this->IsTrash;
}

function getSendType()
{
return $this->SendType;
}

function getRecType()
{
return $this->RecType;
}

// **********************
// SETTER METHODS
// **********************


function setID($val)
{
$this->ID =  $val;
}

function setMailBoxID($val)
{
$this->MailBoxID =  $val;
}

function setSenderID($val)
{
$this->SenderID =  $val;
}

function setRecipientID($val)
{
$this->RecipientID =  $val;
}

function setSubjectID($val)
{
$this->SubjectID =  $val;
}

function setSubject($val)
{
$this->Subject =  $val;
}

function setBody($val)
{
$this->Body =  $val;
}

function setSentOn($val)
{
$this->SentOn =  $val;
}

function setReadOn($val)
{
$this->ReadOn =  $val;
}

function setDeletedOn($val)
{
$this->DeletedOn =  $val;
}

function setStatus($val)
{
$this->Status =  $val;
}

function setReplyID($val)
{
$this->ReplyID =  $val;
}

function setIsRead($val)
{
$this->IsRead =  $val;
}

function setIsDeleted($val)
{
$this->IsDeleted =  $val;
}

function setIsTrash($val)
{
$this->IsTrash =  $val;
}

function setSendType($val)
{
$this->SendType =  $val;
}

function setRecType($val)
{
$this->RecType =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM messages WHERE ID = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->ID = $row->ID;

$this->MailBoxID = $row->MailBoxID;

$this->SenderID = $row->SenderID;

$this->RecipientID = $row->RecipientID;

$this->SubjectID = $row->SubjectID;

$this->Subject = $row->Subject;

$this->Body = $row->Body;

$this->SentOn = $row->SentOn;

$this->ReadOn = $row->ReadOn;

$this->DeletedOn = $row->DeletedOn;

$this->Status = $row->Status;

$this->ReplyID = $row->ReplyID;

$this->IsRead = $row->IsRead;

$this->IsDeleted = $row->IsDeleted;

$this->IsTrash = $row->IsTrash;

$this->SendType = $row->SendType;

$this->RecType = $row->RecType;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM messages WHERE ID = $id;";
$result = $this->database->query($sql);

}


// sets null if blank
function _set_null_default_value($value) {
	if ($value == '') {
		return "NULL";
	} else {
		return "'".$value."'";
	}
}

function _set_zero_default_value($value) {
	if ($value == '') {
		return 0;
	} else {
		return "'".$value."'";
	}
}
// **********************
// INSERT
// **********************

function insert() {
	$this->ID = ""; // clear key for autoincrement

	if ($this->SubjectID == '') {
		$subject_id = "null";
	} else {
		$subject_id = "'".$this->SubjectID."'";
	}

	if ($this->SentOn == '') {
		$sent_on = "null";
	} else {
		$sent_on = "'".$this->SentOn."'";
	}

	if ($this->ReadOn == '') {
		$read_on = "null";
	} else {
		$read_on = "'".$this->ReadOn."'";
	}

	if ($this->DeletedOn == '') {
		$deleted_on = "null";
	} else {
		$deleted_on = "'".$this->DeletedOn."'";
	}

	if ($this->Status == '') {
		$status = "null";
	} else {
		$status = "'".$this->Status."'";
	}

	$reply_id = $this->_set_null_default_value($this->ReplyID);
	$is_read = $this->_set_zero_default_value($this->IsRead);
	$is_deleted = $this->_set_zero_default_value($this->IsDeleted);
	$is_trash = $this->_set_zero_default_value($this->IsTrash);

	$sql = "INSERT INTO messages ( MailBoxID,SenderID,RecipientID,SubjectID,Subject,Body,SentOn,ReadOn,DeletedOn,Status,ReplyID,IsRead,IsDeleted,IsTrash,SendType,RecType ) VALUES ( '$this->MailBoxID','$this->SenderID','$this->RecipientID',$subject_id,'$this->Subject','$this->Body',$sent_on,$read_on,$deleted_on,$status,$reply_id,$is_read,$is_deleted,$is_trash,'$this->SendType','$this->RecType' )";
	$result = $this->database->query($sql);
	$this->ID = mysqli_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE messages SET  MailBoxID = '$this->MailBoxID',SenderID = '$this->SenderID',RecipientID = '$this->RecipientID',SubjectID = '$this->SubjectID',Subject = '$this->Subject',Body = '$this->Body',SentOn = '$this->SentOn',ReadOn = '$this->ReadOn',DeletedOn = '$this->DeletedOn',Status = '$this->Status',ReplyID = '$this->ReplyID',IsRead = '$this->IsRead',IsDeleted = '$this->IsDeleted',IsTrash = '$this->IsTrash',SendType = '$this->SendType',RecType = '$this->RecType' WHERE ID = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
